# .fetch\(\)

## 176 - A Better Way: Fetch!

### .fetch\(\) **SUPPORTS** Promises

### Promises are **USEFUL** especially when we're making **MULTIPLE** requests

* This is how .fetch\(\) looks like and this also explains **how to know what's inside of the object**

```javascript
fetch('https://icanhazdadjoke.com/23/2', {
  headers: { Accept: 'application/json' }, // This returs a promise
})
  .then((response) => {
    // If the response is not 200 then exit
    if (response !== 200) {
      console.log('Problem!', response.status);
      return;
    }
    // Due to the if condition above, this will only run if response === 200
    response.json().then((data) => {
      console.log(data);
    });
  })
  .catch(function (error) {
    console.log('Fetch error:', error);
  });
```

#### ! Promise return from .fetch\(\) won't reject on HTTP error status like 404 or 500. It'll return as resolved

* It **only rejects** on **network failure** or **if anything prevents it from completing**
* Basically as long as it gets a **response**, the Promise is considered as **resolved**
* Use `!response.ok` & `response.status` to provide an **error message** in resolve

#### ! To gain access to .catch\(\), we need to throw new Error inside of .then\(\)

```javascript
fetch('https://swapi.co/api/planetsdsfse')
  .then((response) => {
    if (!response.ok) {
      throw new Error(`Error not status 200, status: ${response.status}`);
    } else {
      response.json().then((data) => {
        for (let planet of planets) {
          console.log(planet.name);
        }
      });
    }
  })
  .catch((error) => {
    console.log('Something went wrong', error);
  });
```

## 177 - Chaining Fetch Requests

### If you can attach .then\(\) to it then you can return it and create another .then\(\) on the same level as the first one

```javascript
fetch('www.something.com')
  .then((response) => {
    if (!response.ok === 200) {
      throw new Error(`Error code: ${response.status}`);
    }
    return response.json(); // response.json() returns a promise
  })
  .then((data) => console.log(data))
  .catch((error) => console.log(error));
```

## 178 - Refactoring Fetch Chains

### `Promise.resolve()` comes in handy especially when we want to return a promise in a function.

